require: rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'config/**/*'
    - './**/*_spec.rb'
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Layout/LineLength:
  Max: 200

